# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d3a0943c633ff65921954ce082c0f837442de7f119c72fbb480d136a895705a6fe56387dfe9ad0fe9d25a30f441e71652df9879899c42df68e680680be6600

test:
  secret_key_base: 3df9b74261a0433171fb9913a4300cc2a8a50c35264874a488b82eeef13bc08d5a5c1bba71a1822cf2322087e466369c53eb4c90a6a415348e2558fbc0af9e80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
